# Generated by Django 2.2.1 on 2019-05-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('email_addr', models.EmailField(max_length=254)),
                ('identity', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('protrait', models.ImageField(upload_to='uploads/')),
                ('research_interests', models.TextField()),
                ('cv', models.FileField(upload_to='uploads/')),
                ('join_date', models.DateField()),
                ('leave_date', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
